POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "name-abhi",
    "userName": "Abhijeet30",
    "email": "abhii@g.com",
    "password": "Pallavi@1710",
    "phoneNumber": "7558348607",
    "address": "At Sakori",
    "profilePicture": "pic"
}

###

POST http://localhost:3000/user/update
Content-Type: application/json

{
    "userId": 17,
    "tagLine": "Chasing Excellence",
    "company": "Infosys Ltd."
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "pallavii@g.com",
    "password": "Pallavi@1710"
}

###


GET http://localhost:3000/users HTTP/1.1

###















GET http://localhost:3000/default HTTP/1.1

###


